# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus






main:
  - label: Home
    title: Página inicio Caledonian.
    path: homepage
    class: first
  - label: Exámenes
    path: page/examenes-oficiales
    submenu:
      - label: Cambridge
        path: cambridgesessions
      - label: Trinity
        path: trinitysessions/trinity-college-examinations
  - label: Cursos propios
    path: page/cursos-propios
  - label: Contacto
    path: page/contact
  - label: Trabajar en Caledonian
    path: page/work  
